filter:
    excluded_paths: [vendor/*, tests/*, cops/Cops/Model/Routing/UrlGenerator.php]
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    php_pdepend: true
    php_cpd:
       enabled: true
       excluded_dirs: [vendor, tests]
