lannguage: php

php:
  - 5.3
  - 5.4

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

before_install:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --prefer-source

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
