lannguage: php
php:
    - 5.2
script:
    - phpunit --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --access-token="your-token" --format=php-clover coverage.clover
